name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-prtfolio:latest .

    - name: Test Docker Image
      run: docker run -d -p 8080:80 my-portfolio

    - name: Wait for Docker Container
      run: sleep 5  # Wait for 5 seconds for the container to start

    - name: Test Web Application
      run: curl -sSf http://localhost:8080 > /dev/null
